### ISSUE TITLE
Cannot build on Fedora Rawhide out of the box

### ISSUE THREAD

**Issue by russel** [masterthought/dtanks#2]
Trying to build DTanks on a Fedora Rawhide system gives:

Linking...
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -lGLU
/usr/bin/ld: cannot find -lGLEW

which is clearly wrong since:

/usr/lib64/libjpeg.so.62
/usr/lib64/libGLU.so.1
/usr/lib64/libGLEW.so.1.10

are clearly there.

**Comment by kingsleyh** [comment]
I'm just getting ubuntu installed on Parallels for OSX and will try that - I suspect it may have a similar issue.

**Comment by russel** [comment]
I am just trying with Debian Sid… gets the equivalent problem, so Ubuntu will as well:

Linking...
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -lGLEW
collect2: error: ld returned 1 exit status

but:

/usr/lib/x86_64-linux-gnu/libjpeg.so.62
/usr/lib/x86_64-linux-gnu/libGLU.so.1

**Comment by kingsleyh** [comment]
I've got it working on a fresh install of ubuntu - here are the instructions for that:

https://github.com/masterthought/dtanks/wiki/Installation-and-Running

I think you need to make sure libjpeg-dev and libglew-dev are installed in your case

**Comment by russel** [comment]
Dub should be checking this. :-(

**Comment by kingsleyh** [comment]
Is that something I can configure in dub? or do you mean that dub does not support this kind of thing - but it would be nice if it would?

**Comment by kingsleyh** [comment]
I've got it working in Windows now as well - have added instructions to the same wiki page

**Comment by russel** [comment]
Sadly my fear about precompiled libraries:

Compiling using dmd...
Linking...
/usr/bin/ld: warning: libjpeg.so.8, needed by DSFML/Linux64/libdsfml-graphics.so, not found (try using -rpath or -rpath-link)
DSFML/Linux64/libdsfml-graphics.so: undefined reference to `jpeg_std_error@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to`jpeg_set_defaults@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to `jpeg_start_compress@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to`jpeg_set_quality@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to `jpeg_stdio_dest@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to`jpeg_finish_compress@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to `jpeg_CreateCompress@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to`jpeg_destroy_compress@LIBJPEG_8.0'
DSFML/Linux64/libdsfml-graphics.so: undefined reference to `jpeg_write_scanlines@LIBJPEG_8.0'
collect2: error: ld returned 1 exit status

**Comment by kingsleyh** [comment]
ah :(

You can build your own from source here:
https://github.com/Jebbs/DSFML/wiki/Building-DSFML-Libraries-From-Source(Linux)

**Comment by kingsleyh** [comment]
also if your only issue is the libjpeg version - you might just try a cheeky symlink from your version to v8 

—K

**Comment by russel** [comment]
Got a build on Debian – JPEG developer libraries are awkward on Debian as well as Fedora, but:

|> LD_LIBRARY_PATH=DSFML/Linux64 dtanks
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  36
  Current serial number in output stream:  39

**Comment by kingsleyh** [comment]
hmm that looks more like a graphics card driver issue with opengl. does this work?

export LIBGL_DEBUG=verbose
glxgears
check the answer here: 
http://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update http://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update

**Comment by kingsleyh** [comment]
I was speaking to the DSFML guy and actually his guide on building from source is not correct anymore - now it's much easier:

just install cmake and then do this:

```
git clone https://github.com/Jebbs/DSFML-C.git
cd DSFML-C
cmake .
make
```

this will make the binaries that go in the Linux32 or Linux64 directory

**Comment by kingsleyh** [comment]
I've updated the wiki now as well: https://github.com/masterthought/dtanks/wiki/Installation-and-Running

**Comment by kingsleyh** [comment]
I think this should be sorted now with the new wiki guide for building from source
